controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    cherry_bot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster



cherry_bot_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
  joints:
    - joint1
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1